export const AUTH_USER = 'auth_user',  
             UNAUTH_USER = 'unauth_user',
             AUTH_ERROR = 'auth_error',
             FORGOT_PASSWORD_REQUEST = 'forgot_password_request',
             RESET_PASSWORD_REQUEST = 'reset_password_request',
             PROTECTED_TEST = 'protected_test',
             FETCH_ENTITIES_PENDING = 'fetch_entities_pending',
             FETCH_ENTITIES_FULFILLED = 'fetch_entities_fulfilled',
             FETCH_ENTITIES_REJECTED = 'fetch_entities_rejected';